language: node_js

node_js:
  - "4.2"
  
nv:
  - CC=clang CXX=g++-4.8 npm_config_clang=1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8  

git:
  depth: 10

branches:
  only:
    - master

sudo: false

