addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libssl-dev
      - lcov   
      - gcc-4.8
      - g++-4.8
before_install:
  - export CC="gcc-4.8"
  - export CXX="g++-4.8"
language: node_js
node_js:
  - '4.2'
os:
  - linux
sudo: false

  
