language: node_js

node_js:
  - "4.2.2"
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libssl-dev
      - gcc-4.9
      - g++-4.9
      - libc6
      - lcov

git:
  depth: 10

branches:
  only:
    - master

sudo: false

env:
  - CC=clang CXX=clang++ npm_config_clang=1
